### ISSUE TITLE
getting the same card twice

### ISSUE THREAD

**Issue by cgpacifico** [wesdoyle/react-flashcards#1]
forgive me, I'm sure there's better open-source etiquette then posting an "issue" and solution all at once

a quick addition, updating two functions to keep from repeating cards
```
  getRandomCard(currentCards, currentCardIx) {
    let randomIx = Math.floor(Math.random() * currentCards.length)
    if (randomIx == currentCardIx) {
      return this.getRandomCard(currentCards, currentCardIx)
    }
    else {
      var card = currentCards[randomIx];
      return (card);
    }
  }

  updateCard() {
    const currentCardIx = this.state.currentCard.id
    const currentCards = this.state.cards;
    this.setState({
      cards: currentCards,
      currentCard: this.getRandomCard(currentCards, currentCardIx)
    })
  }
```
thanks for your excellent example!

**Comment by wesdoyle** [comment]
Great idea - you're welcome to open a pull request, if you'd like!

**Comment by wesdoyle** [comment]
+cgpacifico - Nice idea. I updated the method to make a recursive call to getRandomCard if the returned card is the same as curentCard in the extant state. I'll mark as resolved.
